FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy seed scripts
COPY simulation ./simulation
COPY seed ./seed

# Run seed script
CMD ["python", "-m", "seed.seed_realestate"]
